name: Test Suites

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
